language: python

sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install --editable .[test]
    - pip install coveralls

script:
    coverage run --source=fabricio -m unittest2 discover tests -v

after_success:
    coveralls

branches:
  only:
    - master
